create table public.country (
  id bigserial not null,
  name character varying(255) not null,
  code character varying(255) not null,
  active boolean default true,
  created_at timestamp default CURRENT_TIMESTAMP,
  updated_at timestamp default CURRENT_TIMESTAMP,
  constraint country_pkey primary key (id),
  constraint country_code_key unique (code)
);

create table public.category (
  id bigserial not null,
  name character varying(255) not null,
  active boolean default true,
  constraint category_pkey primary key (id)
);

create table public.title (
  id bigserial not null,
  name character varying(255) not null,
  description character varying(255),
  min_trips integer,
  min_spent integer,
  created_at timestamp default CURRENT_TIMESTAMP,
  constraint title_pkey primary key (id)
);

create table public.users (
  id bigint generated by default as identity not null,
  active boolean not null,
  created_at timestamp not null,
  deleted boolean not null,
  deleted_at timestamp,
  email character varying(100) not null,
  password character varying(255) not null,
  phone character varying(15),
  role character varying(20) not null,
  updated_at timestamp not null,
  username character varying(50) not null,
  verified boolean not null,
  profile_image_url character varying(255),
  constraint users_pkey primary key (id),
  constraint uk_users_email unique (email),
  constraint uk_users_username unique (username),
  constraint users_role_check check (
    role::text = any (array['USER','PARTNER']::text[])
  )
);

create table public.refresh_tokens (
  id bigint generated by default as identity not null,
  expires_at timestamp not null,
  revoked boolean not null,
  token character varying(200) not null,
  user_id bigint not null,
  constraint refresh_tokens_pkey primary key (id),
  constraint uk_refresh_token unique (token),
  constraint fk_refresh_user foreign key (user_id)
    references users (id) on delete cascade
);

create table public.blacklisted_tokens (
  id bigint generated by default as identity not null,
  expires_at timestamp not null,
  jti character varying(64) not null,
  constraint blacklisted_tokens_pkey primary key (id),
  constraint uk_blacklisted_jti unique (jti)
);


create table public.user_profile (
  user_id bigint not null,
  about character varying(1000),
  explorer_level character varying(30),
  favorite_destination character varying(100),
  updated_at timestamp not null,
  constraint user_profile_pkey primary key (user_id),
  constraint fk_user_profile foreign key (user_id)
    references users (id) on delete cascade
);

create table public.user_stats (
  user_id bigint not null,
  total_trips integer default 0,
  completed_trips integer default 0,
  total_spent integer default 0,
  reward_points integer default 0,
  followers integer default 0,
  updated_at timestamp default CURRENT_TIMESTAMP,
  constraint user_stats_pkey primary key (user_id),
  constraint fk_user_stats foreign key (user_id)
    references users (id) on delete cascade
);

create table public.user_rewards_summary (
  user_id bigint not null,
  total_points integer,
  total_spent numeric(38,2),
  total_trips integer,
  constraint user_rewards_summary_pkey primary key (user_id),
  constraint fk_rewards_user foreign key (user_id)
    references users (id) on delete cascade
);

create table public.user_title (
  id bigserial not null,
  user_id bigint not null,
  title_id bigint not null,
  achieved_at timestamp default CURRENT_TIMESTAMP,
  constraint user_title_pkey primary key (id),
  constraint fk_ut_user foreign key (user_id) references users (id),
  constraint fk_ut_title foreign key (title_id) references title (id)
);


create table public.state (
  id bigserial not null,
  country_id bigint not null,
  name character varying(255) not null,
  code character varying(10),
  active boolean default true,
  created_at timestamp default CURRENT_TIMESTAMP,
  updated_at timestamp default CURRENT_TIMESTAMP,
  image_url character varying(255),
  constraint state_pkey primary key (id),
  constraint fk_state_country foreign key (country_id)
    references country (id) on delete cascade
);


create table public.destination (
  id bigserial not null,
  state_id bigint not null,
  name character varying(255) not null,
  short_description character varying(500),
  full_description text,
  address character varying(255),
  pincode character varying(255),
  latitude numeric(38,2),
  longitude numeric(38,2),
  cover_image_url character varying(255),
  youtube_video_url character varying(255),
  active boolean default true,
  created_at timestamp default CURRENT_TIMESTAMP,
  updated_at timestamp default CURRENT_TIMESTAMP,
  description character varying(255),
  image_url character varying(255),
  constraint destination_pkey primary key (id),
  constraint fk_destination_state foreign key (state_id)
    references state (id) on delete cascade
);

create table public.destination_crowd (
  destination_id bigint not null,
  crowd_level character varying(255) not null,
  crowd_score numeric(38,2),
  updated_at timestamp default CURRENT_TIMESTAMP,
  constraint pk_destination_crowd primary key (destination_id),
  constraint fk_destination_crowd foreign key (destination_id)
    references destination (id) on delete cascade
);

create table public.destination_price (
  destination_id bigint not null,
  adult_price integer,
  child_price integer,
  foreigner_price integer,
  constraint destination_price_pkey primary key (destination_id),
  constraint fk_destination_price foreign key (destination_id)
    references destination (id)
);

create table public.destination_timing (
  id bigserial not null,
  destination_id bigint not null,
  day_of_week integer not null,
  open_time time,
  close_time time,
  closed boolean default false,
  constraint destination_timing_pkey primary key (id),
  constraint fk_dest_timing foreign key (destination_id)
    references destination (id) on delete cascade
);

create table public.destination_image (
  id bigserial not null,
  destination_id bigint not null,
  image_url character varying(255) not null,
  sort_order integer not null,
  created_at timestamp default CURRENT_TIMESTAMP,
  constraint destination_image_pkey primary key (id),
  constraint fk_destination_image foreign key (destination_id)
    references destination (id) on delete cascade
);

create table public.destination_tag (
  id bigserial not null,
  name character varying(100) not null,
  constraint destination_tag_pkey primary key (id),
  constraint uk_destination_tag unique (name)
);

create table public.destination_category (
  destination_id bigint not null,
  category_id bigint not null,
  constraint pk_destination_category primary key (destination_id, category_id),
  constraint fk_dc_destination foreign key (destination_id)
    references destination (id) on delete cascade,
  constraint fk_dc_category foreign key (category_id)
    references category (id) on delete cascade
);



create table public.destination_draft (
  id bigserial not null,
  state_id bigint not null,
  name character varying(255) not null,
  short_description character varying(255),
  full_description character varying(255),
  address character varying(255),
  pincode character varying(255),
  latitude double precision,
  longitude double precision,
  cover_image_url character varying(255),
  youtube_video_url character varying(255),
  status character varying(255) default 'PENDING',
  admin_remark character varying(255),
  created_by bigint not null,
  reviewed_by bigint,
  reviewed_at timestamp,
  created_at timestamp default CURRENT_TIMESTAMP,
  updated_at timestamp default CURRENT_TIMESTAMP,
  constraint destination_draft_pkey primary key (id),
  constraint fk_destination_draft_state foreign key (state_id)
    references state (id) on delete cascade
);

create table public.destination_draft_image (
  id bigserial not null,
  destination_draft_id bigint not null,
  image_url character varying(255) not null,
  sort_order integer not null,
  is_cover boolean default false,
  created_at timestamp default CURRENT_TIMESTAMP,
  constraint destination_draft_image_pkey primary key (id),
  constraint fk_draft_image foreign key (destination_draft_id)
    references destination_draft (id) on delete cascade
);

create table public.journey (
  id bigint generated by default as identity not null,
  created_at timestamp,
  end_date date,
  start_date date,
  status character varying(255),
  total_cost numeric(38,2),
  destination_id bigint not null,
  user_id bigint not null,
  constraint journey_pkey primary key (id),
  constraint fk_journey_user foreign key (user_id)
    references users (id),
  constraint fk_journey_destination foreign key (destination_id)
    references destination (id),
  constraint journey_status_check check (
    status::text = any (
      array['PLANNED','CONFIRMED','COMPLETED','CANCELLED']::text[]
    )
  )
);

create table public.follower (
  id bigint generated by default as identity not null,
  created_at timestamp,
  follower_id bigint not null,
  following_id bigint not null,
  constraint follower_pkey primary key (id)
);


create index idx_destination_state on public.destination (state_id);
create index idx_destination_active on public.destination (active);
create index idx_destination_lat_lon on public.destination (latitude, longitude);

create index idx_dest_image_destination on public.destination_image (destination_id);

create index idx_destination_crowd_updated on public.destination_crowd (updated_at);

create index idx_dc_destination on public.destination_category (destination_id);
create index idx_dc_category on public.destination_category (category_id);

create table user_verification (
  user_id bigint primary key references users(id) on delete cascade,
  email_verified boolean default false,
  phone_verified boolean default false,
  created_at timestamptz default now()
);

create table host_verification (
  id bigserial primary key,
  user_id bigint not null references users(id) on delete cascade,
  aadhaar_hash text not null,
  pan_hash text not null,
  status text check (status in ('PENDING','VERIFIED','REJECTED')) default 'PENDING',
  rejection_reason text,
  verified_at timestamptz,
  created_at timestamptz default now(),
  unique (user_id)
);

create table business_verification (
  id bigserial primary key,
  user_id bigint not null references users(id) on delete cascade,
  gst_hash text not null,
  business_name text not null,
  registered_address text not null,
  status text check (status in ('PENDING','VERIFIED','REJECTED')) default 'PENDING',
  rejection_reason text,
  verified_at timestamptz,
  created_at timestamptz default now(),
  unique (user_id)
);

create table stay_draft (
  id bigserial primary key,
   host_user_id bigint not null references users(id),
  title text not null,
  description text,
  full_address text not null,
  country_id bigint,
  state_id bigint,
  latitude numeric(9,6),
  longitude numeric(9,6),
  property_type text check (property_type in ('ROOM','HOME','VILLA')),
  status text check (status in ('PENDING_REVIEW','APPROVED','REJECTED')) default 'PENDING_REVIEW',
  rejection_reason text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

CREATE TABLE stay_draft_capacity (
  stay_draft_id BIGINT PRIMARY KEY
    REFERENCES stay_draft(id) ON DELETE CASCADE,

  max_guests INT NOT NULL,
  bedrooms INT DEFAULT 1,
  beds INT DEFAULT 1,
  bathrooms INT DEFAULT 1
);

CREATE TABLE stay_draft_pricing (
  stay_draft_id BIGINT PRIMARY KEY
    REFERENCES stay_draft(id) ON DELETE CASCADE,

  price_per_night NUMERIC(10,2) NOT NULL,

  min_nights INT DEFAULT 1,
  max_nights INT DEFAULT 30,

  check_in_time TIME,
  check_out_time TIME
);

CREATE TABLE amenity_master (
  code TEXT PRIMARY KEY,   -- WIFI, AC, PARKING
  label TEXT NOT NULL,
  icon TEXT
);

CREATE TABLE stay_draft_amenity (
  stay_draft_id BIGINT REFERENCES stay_draft(id) ON DELETE CASCADE,
  amenity_code TEXT REFERENCES amenity_master(code),

  PRIMARY KEY (stay_draft_id, amenity_code)
);



CREATE TABLE stay_draft_media (
  id BIGSERIAL PRIMARY KEY,
  stay_draft_id BIGINT NOT NULL
    REFERENCES stay_draft(id) ON DELETE CASCADE,

  media_type TEXT CHECK (media_type IN ('IMAGE','VIDEO')),
  media_url TEXT NOT NULL,
  sort_order INT,

  created_at TIMESTAMPTZ DEFAULT now()
);



create table stay_admin_review (
  id bigserial primary key,
  stay_draft_id bigint unique references stay_draft(id) on delete cascade,
  admin_user_id bigint references users(id),
  video_call_done boolean default false,
  video_call_notes text,
  decision text check (decision in ('APPROVED','REJECTED')),
  decision_at timestamptz
);

CREATE TABLE stay (
  id BIGSERIAL PRIMARY KEY,

  host_user_id BIGINT NOT NULL REFERENCES users(id),

  title TEXT NOT NULL,
  description TEXT,
  full_address TEXT NOT NULL,

  country_id BIGINT,
  state_id BIGINT,

  latitude NUMERIC(9,6),
  longitude NUMERIC(9,6),

  property_type TEXT CHECK (property_type IN ('ROOM','HOME','VILLA')),

  status TEXT CHECK (status IN ('ACTIVE','SUSPENDED'))
    DEFAULT 'ACTIVE',

  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE stay_capacity (
  stay_id BIGINT PRIMARY KEY REFERENCES stay(id) ON DELETE CASCADE,

  max_guests INT NOT NULL,
  bedrooms INT,
  beds INT,
  bathrooms INT
);


CREATE TABLE stay_pricing (
  stay_id BIGINT PRIMARY KEY REFERENCES stay(id) ON DELETE CASCADE,

  price_per_night NUMERIC(10,2) NOT NULL,
  min_nights INT,
  max_nights INT,

  check_in_time TIME,
  check_out_time TIME
);

CREATE TABLE stay_amenity (
  stay_id BIGINT REFERENCES stay(id) ON DELETE CASCADE,
  amenity_code TEXT REFERENCES amenity_master(code),

  PRIMARY KEY (stay_id, amenity_code)
);

CREATE TABLE stay_media (
  id BIGSERIAL PRIMARY KEY,
  stay_id BIGINT REFERENCES stay(id) ON DELETE CASCADE,

  media_type TEXT CHECK (media_type IN ('IMAGE','VIDEO')),
  media_url TEXT NOT NULL,
  sort_order INT,

  created_at TIMESTAMPTZ DEFAULT now()
);


CREATE TABLE stay_booking (
  id BIGSERIAL PRIMARY KEY,

  stay_id BIGINT NOT NULL REFERENCES stay(id),
  guest_user_id BIGINT NOT NULL REFERENCES users(id),

  check_in_date DATE NOT NULL,
  check_out_date DATE NOT NULL,

  guests_count INT NOT NULL,

  booking_status TEXT CHECK (
    booking_status IN ('PENDING','CONFIRMED','CANCELLED','COMPLETED')
  ) NOT NULL DEFAULT 'PENDING',

  created_at TIMESTAMPTZ DEFAULT now(),

  CHECK (check_out_date > check_in_date)
);

CREATE TABLE stay_booking_price (
  booking_id BIGINT PRIMARY KEY
    REFERENCES stay_booking(id) ON DELETE CASCADE,

  price_per_night NUMERIC(10,2) NOT NULL,
  nights INT NOT NULL,

  base_amount NUMERIC(10,2) NOT NULL,
  service_fee NUMERIC(10,2),
  taxes NUMERIC(10,2),

  final_amount NUMERIC(10,2) NOT NULL
);

CREATE TABLE stay_booking_guest (
  id BIGSERIAL PRIMARY KEY,

  booking_id BIGINT REFERENCES stay_booking(id) ON DELETE CASCADE,

  guest_name TEXT,
  guest_age INT
);

CREATE TABLE stay_payment (
  id BIGSERIAL PRIMARY KEY,

  booking_id BIGINT NOT NULL
    REFERENCES stay_booking(id) ON DELETE CASCADE,

  payment_method TEXT CHECK (
    payment_method IN ('UPI','CARD','NETBANKING','WALLET')
  ),

  payment_status TEXT CHECK (
    payment_status IN (
      'INITIATED',
      'SUCCESS',
      'FAILED',
      'REFUNDED'
    )
  ) NOT NULL,

  transaction_id TEXT,
  amount NUMERIC(10,2),

  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE stay_booking_cancellation (
  booking_id BIGINT PRIMARY KEY
    REFERENCES stay_booking(id) ON DELETE CASCADE,

  cancelled_by TEXT CHECK (
    cancelled_by IN ('GUEST','HOST','SYSTEM')
  ) NOT NULL,

  reason TEXT,
  refund_amount NUMERIC(10,2),

  cancelled_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE stay_availability (
  stay_id BIGINT NOT NULL
    REFERENCES stay(id) ON DELETE CASCADE,

  booking_date DATE NOT NULL,

  status TEXT CHECK (status IN ('BOOKED')) NOT NULL,

  booking_id BIGINT
    REFERENCES stay_booking(id) ON DELETE CASCADE,

  PRIMARY KEY (stay_id, booking_date)
);




CREATE TABLE packages (
    id BIGSERIAL PRIMARY KEY,

    user_id BIGINT NOT NULL,

    title VARCHAR(200) NOT NULL,
    destination VARCHAR(150) NOT NULL,
    package_type VARCHAR(50),

    duration VARCHAR(50),
    starting_price NUMERIC(10,2),

    description TEXT NOT NULL,

    cover_image_url TEXT NOT NULL,

    is_published BOOLEAN DEFAULT TRUE,
    is_approved BOOLEAN DEFAULT TRUE,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_package_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE
);


CREATE TABLE package_images (
    id BIGSERIAL PRIMARY KEY,

    package_id BIGINT NOT NULL,
    image_url TEXT NOT NULL,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_image_package
        FOREIGN KEY (package_id)
        REFERENCES packages(id)
        ON DELETE CASCADE
);

CREATE TABLE package_limits (
    id BIGSERIAL PRIMARY KEY,

    user_id BIGINT NOT NULL,

    total_allowed INT DEFAULT 3,   
    total_created INT DEFAULT 0,

    is_subscription_active BOOLEAN DEFAULT FALSE,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_limit_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE,

    CONSTRAINT uq_limit_user UNIQUE (user_id)
);

CREATE TABLE subscriptions (
    id BIGSERIAL PRIMARY KEY,

    user_id BIGINT NOT NULL,

   plan_name VARCHAR(50) DEFAULT 'MONTHLY_199',

    price NUMERIC(10,2),

    start_date DATE,
    end_date DATE,

    is_active BOOLEAN DEFAULT FALSE,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_subscription_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE
);


CREATE INDEX idx_packages_user ON packages(user_id);
CREATE INDEX idx_packages_destination ON packages(destination);
CREATE INDEX idx_images_package ON package_images(package_id);
CREATE INDEX idx_limits_user ON package_limits(user_id);







